ibkr:
  host: "127.0.0.1"
  port: 7497
  clientId: 0


zoneTime: "America/New_York"

sesion:
  ini: "09:30"
  fin: "16:00"

OperationTime:
  
  Entryini: "09:30" #"09:30"
  Entryfin: "23:59"

  OutTime: "14:50"

  iniScan: "00:00"  #por ahora 00:00 
  finScan: "22:00"  

Scanner:
  
  code:             "TOP_PERC_GAIN"
  instrument:       "STK"
  location_code:    "STK.US.MAJOR"
  number_Symbol:    5   #50s
  above_price:      0.5 
  below_price:      100
  above_volume:     20_000 #

  market_cap_below: 5_000  #2 000 000 000 El valor es en millones
  market_cap_above: 5  #50

ParamOp:
  minProb:  20  # x %
  minHeap:  10  # x %
  
  autoData: "NO"
  autoTick: "SI"

Stop:
  tipo: "PERC"
  Kst:  5

TakeP:
  tipo: "BR"
  Ktp:  2


Mm:
  tipo: "FIX"
  val:  100

  cartera: 30_000

System:
  Strategy:   "S00"
  Algoritmo:  "A00"
