[pytest]
addopts = -ra
filterwarnings =
    # Silence pytest-asyncio default loop scope deprecation (can address later explicitly)
    ignore::pytest.PytestDeprecationWarning
    # Ignore DeprecationWarning from eventkit util awaiting loop
    ignore::DeprecationWarning
